# Generated by Django 3.1.2 on 2020-10-20 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_newsconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsConfig',
        ),
    ]
