# Generated by Django 3.1.2 on 2020-10-20 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_newsconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteConfig',
        ),
    ]
